/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef scribe_CONSTANTS_H
#define scribe_CONSTANTS_H

#include "scribe_types.h"

namespace scribe { namespace thrift {

class scribeConstants {
 public:
  scribeConstants();

};

extern const scribeConstants g_scribe_constants;

}} // namespace

#endif
